spring:
  application:
    name: client-fidelity
  jackson:
    deserialization:
      fail-on-unknown-properties: true
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
      path: /h2-console

client-fidelity:
  persistence:
    type: h2
    csv:
      path: ./data/users.csv
